### ISSUE TITLE
BUG ? MainsailOS 0.6.1 Not connecting to Moonraker

### ISSUE THREAD

**Issue by SISLANGER** [mainsail-crew/MainsailOS#100]
Running a fresh install from: MainsailOS-buster-lite-0.6.1 I cant get past Connection error as it is not connecting to Moonraker.

Cannot connect to Moonraker (mainsailos.local).

But if I install from 0.50 I have no issues.

2022-03-15 11:27:04,372 [web.py:log_exception()] - 401 GET /websocket (...): Unauthorized
2022-03-15 11:27:04,375 [app.py:log_request()] - 401 GET /websocket (...) [No User] 17.31ms

**Comment by meteyou** [comment]
Pls Upload your moonraker logfile

**Comment by SISLANGER** [comment]
@meteyou 

[moonraker.log](https://github.com/mainsail-crew/MainsailOS/files/8253454/moonraker.log)

**Comment by meteyou** [comment]
Pls Upload it again with your IP address. I have to check your settings with your requests

**Comment by SISLANGER** [comment]
@meteyou all the ip addresses in the moonraker.log were the same, which is my current ip address. 
(Only a single replace all matching was used)

**Comment by meteyou** [comment]
Pls tell me your address. I have to compare the trusted range with your address

**Comment by meteyou** [comment]
ok. then you have to add `2a02:c7f:890:c100::/64` as trusted client in your moonraker.conf. mainsailOS > 0.6.x have ipv6 enabled and your client will connect via ipv6, but you router dont use a "standard" ipv6 network for your local address range.

**Comment by meteyou** [comment]
do you restarted moonraker? if you have the same issue also after a moonraker restart, pls upload your COMPLETE logfile again.

as i told you above. v0.5.x have no ipv6 support and your client try to use IPv6...

**Comment by SISLANGER** [comment]
yes, but I now done a full shutdown and it is now working. 

I know you said 0.5 doesnt use ipv6 but as I said, I updated it to 0.6.1 (on another SD card, same pi) and it worked without needing to add to trusted client. Does the update do this automatically? If so they would make sense.

**Comment by meteyou** [comment]
there is no function to update mainsailOS settings. an up-to-date mainsailOS 0.5 is a mainsailOS 0.5. you have the same "old" nginx settings as before
