### ISSUE TITLE
connection issues

### ISSUE THREAD

**Issue by Fuckingnameless** [mainsail-crew/MainsailOS#104]
often when i turn on the pi NOT at the same time as the printer it doesn´t connect 

using cabled network

**Comment by KwadFan** [comment]
Hey, there.

Sorry for the late answer, but this is a bit vague, what dosnt connect? Could you explain it further what exactly happend ? How to reproduce? And so forth..

Regards

**Comment by meteyou** [comment]
pls, use our discord server for support: discord.gg/mainsail

we use Github issues only for bugs or feature reqeusts.
