### ISSUE TITLE
JVC webcam issue, not working with crowsnest

### ISSUE THREAD

**Issue by richar43** [mainsail-crew/MainsailOS#174]
### What happened

JVC webcam (model : JVCU100) I have installed crowsnest, and still am unable to view webcam. Here is my crowsnest. log

### What did you expect to happen

Working webcam

### How to reproduce

Unable to view webcam in mainsail

### Additional information

[crowsnest (3).log](https://github.com/mainsail-crew/MainsailOS/files/10079185/crowsnest.3.log)

**Comment by meteyou** [comment]
pls report crowsnest issues in the crowsnest repo.
