### ISSUE TITLE
Layout reset confirmation

### ISSUE THREAD

**Issue by leitenky** [mainsail-crew/MainsailOS#194]
### Is your feature request related to a problem? Please describe

I accidently hit the reset layout button in Settings > dashboard, and reset my dashboard layout

### Describe the solution you'd like

If you click the reset layout button have a confirmation dialog pop up

**Comment by KwadFan** [comment]
Hey @leitenky ,

Thanks for the Feature Request. But I'll have to apologize, this will be closed.

Please use https://github.com/mainsail-crew/mainsail for GUI related feature requests or issues.

This repo contains files related to the underlying OS not the GUI.
Sorry for inconvenience.
