### ISSUE TITLE
Sonar can’t find its conf file 

### ISSUE THREAD

**Issue by asm308** [mainsail-crew/MainsailOS#195]
### What happened

I built the rpi ssd card from the downloadable image just before Christmas as per voron build instructions.  I was having a lot of trouble with my wifi constantly dropping connections every few minutes.  Anyway after a lot of false starts when I thought I had a wifi problem I eventually found sonar to be the culprit.  
Looking at the sonar.conf file in the klipper dashboard it should have been disabled but in fact it wasn’t finding its conf file because it’s looking for it in the wrong place.  The libs/core.sh file uses the path ${BASE_USER_HOME}/klipper_config/sonar.conf when in fact it should have been looking in printer_data/config/sonar.conf.  Now that I’ve changed the code it finds its config file and honours the disabled state which means my wifi stays up for more than a few minutes at a time.  The problem is in a couple of places in core.sh

### What did you expect to happen

I expected sonar not to be running

### How to reproduce

If you create a new Ssd card from the image from just before Xmas, run it all up and you will find sonar running even though it’s default config is to disable it

**Comment by KwadFan** [comment]
Hey, sorry for my late respond. I am a bit busy right now.

Could you please move that issue to the sonar repo please?
I will look after asap.

Thank you alot...

Regards Kwad
