### ISSUE TITLE
Bed mesh timestamp

### ISSUE THREAD

**Issue by s3638844** [mainsail-crew/MainsailOS#198]
### Is your feature request related to a problem? Please describe

Not a problem, but would be convenient to have the heightmap console show the timestamp of the mesh for people like me who can't remember their breakfast come dinner.

### Describe the solution you'd like

timestamp could be anywhere in the table of mesh's

### Describe alternatives you've considered

not sure there is an alternative, but if a macro can force the name of a mesh to be the timestamp, can you point me to a clue as to how to pull this info from the OS into the configs as a var

**Comment by meteyou** [comment]
Sorry, but you are here in the wrong place.

MainsailOS is just a preinstalled Raspberry Pi image. There are no FRs for klipper or Mainsail available. Mainsail itself would be the GUI, but Mainsail can only display data which exists in klipper or moonraker. So bed_mesh is a klipper function, and the data comes from the klipper config, but there is no timestamp to display. So please create an FR for Klipper. When this exists, we can implement it in Mainsail.
