### ISSUE TITLE
Klipper make menuconfig fails with unsupported locale setting error

### ISSUE THREAD

**Issue by jypa** [mainsail-crew/MainsailOS#199]
### What happened

Fresh install of MainsailOS 64-bit

Started the Klipper build configuration

```
cd ~/klipper/
make menuconfig
```

Got this error

```
Using default symbol values (no '/home/pi/klipper/.config')
Configuration saved to '/home/pi/klipper/.config'
  Creating symbolic link out/board
Loaded configuration '/home/pi/klipper/.config'
Traceback (most recent call last):
  File "/home/pi/klipper/lib/kconfiglib/menuconfig.py", line 3281, in <module>
    _main()
  File "/home/pi/klipper/lib/kconfiglib/menuconfig.py", line 661, in _main
    menuconfig(standard_kconfig(__doc__))
  File "/home/pi/klipper/lib/kconfiglib/menuconfig.py", line 705, in menuconfig
    locale.setlocale(locale.LC_ALL, "")
  File "/usr/lib/python3.9/locale.py", line 610, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
make: *** [Makefile:116: menuconfig] Error 1
```

**Workaround**
Export locale before `make menuconfig`
```
export LC_ALL=C
```

### What did you expect to happen

Expected Klipper's build configuration menu to appear.

An error message was given.

### How to reproduce

Install a fresh MainsailOS with Raspberry Pi Imager without defining the locale.

### Additional information

This also can be reproduced when there is a locale defined in the Raspberry Pi Imager settings.

**Comment by KwadFan** [comment]
Hey, there. That is not an Issue related to the OS itself.

The rootcause is the setup of your SSH Client which transfers your set locale to the SSH server to tell which local is used.
This bug ist related to klipper and well known for a felt decade.

Please set the same locale on your pi using raspi-config. This should prevent that error. If it does not help, please open a ticket at klipper repo.

The only thing we could do is setting make as an alias together with fallback locale (LC_ALL=C) which we dont want todo for obvious reasons.

Regards Kwad
