### ISSUE TITLE
input shape

### ISSUE THREAD

**Issue by docemiel** [mainsail-crew/MainsailOS#232]
### What happened

orangepi 3lts
new install mainsailos! good!

the script off klipper for input shape

sudo apt update
sudo apt install python3-numpy python3-matplotlib libatlas-base-dev  -  good too

the script to numpy

~/klippy-env/bin/pip install -v numpy     -  do not work, do not install

### What did you expect to happen

the correct install

### How to reproduce

orangepi 3lts
new install mainsailos! good!

the script off klipper for input shape

sudo apt update
sudo apt install python3-numpy python3-matplotlib libatlas-base-dev  -  good too

the script to numpy

~/klippy-env/bin/pip install -v numpy     -  do not work, do not install

**Comment by meteyou** [comment]
All you need for input shaper is preinstalled in MainsailOS and the pip install numpy is only necessary if you don't have a python-numpy package.

**Comment by docemiel** [comment]
everything I need is pre-installed, ok. Let's see if I understand! when installing mainsailos, don't I need to run these lines in the terminal?

**Comment by meteyou** [comment]
All packages should be installed and ready to use.

**Comment by docemiel** [comment]
ok, thanks, i am going to try

**Comment by meteyou** [comment]
@docemiel please, write a short feedback after your test.
