### ISSUE TITLE
UI issue with mobile menu collapse

### ISSUE THREAD

**Issue by AndyHazz** [mainsail-crew/MainsailOS#236]
### What happened

On mobile (or small screen) click the hamburger menu icon to open the nav, then click anywhere outside to close it - the rest of the  UI stays squashed up to the side. Clicking the hamburger icon again restores the layout.

### What did you expect to happen

The layout should go full width as soon as the menu collapses - clicking the hamburger again should reopen the menu.

### How to reproduce

Open and close the menu in the mobile layout.

### Additional information

Increasing the z-index on the header bar (e.g. to 10) keeps the hamburger above the menu so you can open and close by clicking that.

**Comment by meteyou** [comment]
First of all, this is the wrong repo for mainsail bugs. Mainsail is the webgui. MeinsailOS is only a preinstalled SBC image.

This bug is already fixed with this PR: https://github.com/mainsail-crew/mainsail/pull/1518

Thx for the report!
