### ISSUE TITLE
neofetch showing raspbian ascii art instead of mainsail ascii art

### ISSUE THREAD

**Issue by Online122228** [mainsail-crew/MainsailOS#251]
### Is your feature request related to a problem? Please describe

neofetch only shows raspbian logo, because /etc/os-release is entirely set to raspbian 11

### Describe the solution you'd like

one could change the default /etc/os-release so neofetch ascii art can be added to neofetch

### Additional information ###

i know it partly is an issue with neofetch but it reads this file and if it is identical to raspbian, it has no choice but show the raspbian logo. possible idea for /etc/os-release attached
[os-release.txt](https://github.com/mainsail-crew/MainsailOS/files/13199423/os-release.txt)

**Comment by meteyou** [comment]
pls use a short headline and use the description to describe your issue as good as possible.

PS: kwadfan will answer here with a real feedback...

**Comment by KwadFan** [comment]
We can not change the os-release file. This would require we alter all packages from Raspberry Foundation/armbian/orange-pi to not disrupt possible workflows that relie on the original os-release file.

If you want to show it in neofetch, you should consider to seperate that and also looking for `/etc/mainsailos-release`file ...

Other than that I wouldnt describe it as an issue if a thirdparty tool (even I love neofetch too) related to the OS.

Therefore, closing that, sorry mate but out of our scope...

**Comment by Online122228** [comment]
I created a fork of neofetch and after changing the /etc/os-release back, it still worked and showed the mainsailOS ascii-logo i created, so i read a bit about it and found out that neofetch actually looks for files like the /etc/mainsailos-release. So if one wants neofetch with mainsailOS ascii art(small version included) you can find it at github.com/online122228/neofetch

**Comment by KwadFan** [comment]
> I created a fork of neofetch and after changing the /etc/os-release back, it still worked and showed the mainsailOS ascii-logo i created, so i read a bit about it and found out that neofetch actually looks for files like the /etc/mainsailos-release. So if one wants neofetch with mainsailOS ascii art(small version included) you can find it at github.com/online122228/neofetch

You really should consider to PR to dylana's repo ...
Thanks for your work

**Comment by Online122228** [comment]
Already did and created a .deb file
