### ISSUE TITLE
No GPIO access

### ISSUE THREAD

**Issue by GePo00** [mainsail-crew/MainsailOS#252]
### Is your feature request related to a problem? Please describe

The pin’s cannot be used in a macro. 
ex. 
[mcu rpi]
serial: /tmp/klipper_host_mcu
Doesn’t work because the klipper_host_mcu service is not available.

### Describe the solution you'd like

Include start of klipper_host_mcu service into your build.

**Comment by meteyou** [comment]
You have to install and "flash" the host MCU first. This part is not preinstalled on MainsailOS.

Guide: https://www.klipper3d.org/RPi_microcontroller.html
