### ISSUE TITLE
crowsnest.conf not updated for non-pi user

### ISSUE THREAD

**Issue by john3300** [mainsail-crew/MainsailOS#262]
### What happened

I installed Mainsail OS using the Raspberry Pi Imager, but I changed the user to something other than the default 'pi'. I noticed that the crowsnest.conf still references the default pi user in:
`log_path: /home/pi/printer_data/logs/crowsnest.log`.

### What did you expect to happen

I expected the `/home/pi` path to be updated for the non-default user.

### How to reproduce

Install Mainsail OS using the Raspberry Pi Imager and a non-default user.

**Comment by KwadFan** [comment]
Have to do some tests, but I rename my user usually and it never happend to me.
Possible you didnt wait long enough to let "postrename" script to finish.

**Comment by KwadFan** [comment]
Ok, I think I forgot something...
#235

**Comment by KwadFan** [comment]
This could be closed, already fixed, merged and released...
