### ISSUE TITLE
Price and spool management

### ISSUE THREAD

**Issue by nico97472-lab** [mainsail-crew/MainsailOS#283]
### Is your feature request related to a problem? Please describe

I use spoolman but I find it poorly integrated with mainsailos

### Describe the solution you'd like

I would find it interesting if it was possible to be able to find the price of the printing (filament and/or electricity) in the printing history.

### Describe alternatives you've considered

I think we could either:
- make a filament manager on mainsail Os (time-consuming if the project is not already underway on your side)
- or integrate spoolman and calculate them from the API. (Spoolman is under MIT license)

**Comment by meteyou** [comment]
MainsailOS is only a pre installed SBC image. Nothing more. So this is the wrong repository for feature requests like this.
