### ISSUE TITLE
SSH No Work

### ISSUE THREAD

**Issue by thiagomagamoc** [mainsail-crew/MainsailOS#307]
### What happened

I just did a fresh install on a reliable and original card.
My Wifi works fine.
I can connect to the WEB interface
However, SSH does not work
I used NMAP to check for open ports, port 22 was not found.

### What did you expect to happen

Connect via SSH Using Putty (Port 22)

### How to reproduce

Install MainsailOS version 1.3.2 on Orange Pi Zero 2 and try connecting via SSH

### Additional information

![image](https://github.com/user-attachments/assets/5911e335-6f04-4256-90f3-bd9c741af7f2)
![image](https://github.com/user-attachments/assets/45f76446-62ad-4de1-9d58-800718aba08c)
![image](https://github.com/user-attachments/assets/9c1e83cc-4275-4cfb-9000-362458c443d5)
![image](https://github.com/user-attachments/assets/01639df6-f46b-43bd-a96c-a4d10916ea94)

**Comment by meteyou** [comment]
i checked it right now and it works like it should.

- downloaded the current release for the opi zero 2
- flashed with balenaEtcher
- changed network settings in the boot partition
- put sd card in the opi zero 2, plug in power and wait until it booted up
- connect via SSH with user pi and password armbian

![image](https://github.com/user-attachments/assets/e0c5f9c1-8457-49dc-8e33-a688e580e2c8)
