### ISSUE TITLE
FR: Select multiple GCODE Files to delete them

### ISSUE THREAD

**Issue by Markus-1984** [mainsail-crew/MainsailOS#67]
Hi Mainsail-Crew,

it would be very pleasant to select more than one file to delete them instead of do it file by file.

Best regards
Markus

**Comment by meteyou** [comment]
We had a quote about features of v2.1 and multi select have too less votes maybe it will come in V2.2.

**Comment by Markus-1984** [comment]
Thanks for the feedback.
I hope it will come.
