### ISSUE TITLE
Webcam isn't stable // uses a lot of CPU//crashes system

### ISSUE THREAD

**Issue by nickeeey** [mainsail-crew/MainsailOS#82]
Hi, i use a c270 webcam with Moonraker and a Raspberry Pi 3b+. The Webcam worked perfectly at octoprint, but won't work right with Moonraker. I see the picture/ Video after startup but when i switch 2-3 times to the dashboard it just loads. Also my cpu power is going up and i can't access files from the server. I tried different resoultions and framerates

**Comment by meteyou** [comment]
I also use the c270 on 2 printers without issues.

**Comment by nickeeey** [comment]
Can you upload your settings?
I dont know what to do. I also reinstalled the whole system without any positive results.
I think you use the normal mjpeg?

**Comment by meteyou** [comment]
All default settings

**Comment by KwadFan** [comment]
> I think you use the normal mjpeg?

Yes, MainsailOS uses mjpeg-streamer as default.
It is hard for me to reproduce due the fact I dont own Logitech Cams.

Are you able to describe what happend exactly when the system freezes?

Regards

**Comment by nickeeey** [comment]
So i boot up the System and everything is working fine. Then my host is going for 30-50% on the circle at the machine tab. The Load is 1.3 or so and after a few minutes the Video is an endless loading circle. Also my prints stop because of the high load at the raspberry. When i print without Cam i get at max 20% i mean the 3b+ is more than enough for klipper

**Comment by KwadFan** [comment]
So, we are hunting for that, we have a trace to the Problem. Please be patient. We are looking for a solution.
But, yes, basicly it is the same service for the webcam like in Octoprint ( besides Octos HLS Mode ).
The only thing what is different is the location of the configuration file.

Used Software behind that is jacksonliam's mjpg-streamer-experimental

So, give us some time to fix that.

Regards

**Comment by nickeeey** [comment]
> So, we are hunting for that, we have a trace to the Problem. Please be patient. We are looking for a solution.
> But, yes, basicly it is the same service for the webcam like in Octoprint ( besides Octos HLS Mode ).
> The only thing what is different is the location of the configuration file.
> 
> Used Software behind that is jacksonliam's mjpg-streamer-experimental
> 
> So, give us some time to fix that.
> 
> Regards

Thank you very much!
Just tell me if I can do anything for you. Maybe a video or sth?

**Comment by nickeeey** [comment]
i opened cura and saw that there the webcam is still working. (Maybe from the Octoprint before). So there seems to be just a problem inside Mainsail os or the double stream is causing problems

**Comment by meteyou** [comment]
it cannot be a problem inside of mainsailOS, because it is running in cura.

**Comment by juslex** [comment]
Same problem here with c920

**Comment by nickeeey** [comment]
I sold my printer and got a new one. On that it worked perfectly.
If you want I can send you my config

**Comment by KwadFan** [comment]
Hey there,

Please keep in mind that, the higher the Resolution and the higher the framerate someone has to do the Job. In that case there is more or less no hardware accel in mjpg streamer. Please try out our future replacement.

https://github.com/mainsail-crew/crowsnest

The existing solution is quite old and the used backend isn't maintained anymore. So we decided to switch to a activly maintained solution called ustreamer as backend.

Regards

**Comment by meteyou** [comment]
closed because of no response
