### ISSUE TITLE
GCode tumbnail is not rendered

### ISSUE THREAD

**Issue by Aussie84d** [mainsail-crew/MainsailOS#87]
![image](https://user-images.githubusercontent.com/35589893/150695917-ce813ae7-00b1-4017-bbab-77fab7c31851.png)

![image](https://user-images.githubusercontent.com/35589893/150695842-752660b1-dd60-4f2d-9502-f3f28c7cf38a.png)

**Comment by KwadFan** [comment]
Hello, thank you for that report.

But this isnt an MainsailOS Issue, this Bugtracker is only for Issues around mainsail (GUI) related Issue.
So, please report that here: https://github.com/mainsail-crew/mainsail/issues

Also, meteyou informed me that you should upgrade to Version 2.1.

Regards

**Comment by Aussie84d** [comment]
Thank you. I will bring this there
![image](https://user-images.githubusercontent.com/35589893/150705161-8471a4bf-a3d3-47ef-9392-b06f984e98b3.png)
