### ISSUE TITLE
Firmware restart button label shows localization string

### ISSUE THREAD

**Issue by rlaferla** [mainsail-crew/MainsailOS#88]
Instead of the actual text, it is showing the localization variable.
<img width="323" alt="image" src="https://user-images.githubusercontent.com/1135694/151079344-8cfd9912-7583-4774-939a-d33d37d492c8.png">

**Comment by meteyou** [comment]
this repositority is only for the raspberry pi bundle of klipper, moonraker & mainsail. for mainsail issues, pls use the repositority of https://github.com/mainsail-crew/mainsail
