### ISSUE TITLE
On RPI 4 B im getting soft temp limit warnings which do not apply to rpi 4

### ISSUE THREAD

**Issue by gurusonwheels** [mainsail-crew/MainsailOS#94]
getting these warnings in mainsail web 
running mailsailos .

rPi uC (3A+/3B+ only) temperature was at least once above the soft limit (default 60C) since last power-on.

i was under the impression that soft temp limits do not apply to RPI 4 any longer . 

![softlimit](https://user-images.githubusercontent.com/3314914/154369180-44ff65ad-bc77-4ba1-937a-fb6ea6a510d1.png)

**Comment by meteyou** [comment]
this flag will be generated/checked by the raspberry command vcgencmd. moonraker just reads this flags (https://moonraker.readthedocs.io/en/latest/web_api/#get-moonraker-process-stats) and push it to mainsail.

i dont cannot see, why the 4b should not create this flag. in the official docs are no limitation. https://www.raspberrypi.com/documentation/computers/os.html#vcgencmd

but if you think it is wrong, please report it to the raspberry pi foundation itself. they provide this tool.
